# 1. Tensorflow

In [21]:
import tensorflow as tf
from tensorflow.keras import preprocessing
from tensorflow.keras import layers
from tensorflow.keras import backend
import numpy as np

In [24]:
samples = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']
targets = [[1], [0], [1], [1], [0], [1]]

tokenizer = preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(samples)
sequences = tokenizer.texts_to_sequences(samples)
input_sequences = np.array(sequences)
labels = np.array(targets)

word_index = tokenizer.word_index

In [25]:
batch_size = 2
num_epochs = 100
vocab_size = len(word_index) + 1
emb_size=128
hidden_dimension=256
output_dimension=1

In [26]:
model = tf.keras.Sequential()
model.add(layers.Embedding(vocab_size, emb_size, input_length=4))
model.add(layers.Lambda(lambda x:tf.reduce_mean(x, axis=1))) #lambda : 임베딩된 벡터를 평균하기 위함
model.add(layers.Dense(hidden_dimension, activation="relu"))
model.add(layers.Dense(output_dimension, activation="sigmoid"))

In [27]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss="binary_crossentropy", metrics=['accuracy'])

In [29]:
model.fit(input_sequences, labels, epochs=num_epochs, batch_size=batch_size)

Epoch 1/100
3/3 [==============================] - 2s 11ms/step - loss: 0.6910 - accuracy: 0.6667
Epoch 2/100
3/3 [==============================] - 0s 8ms/step - loss: 0.6723 - accuracy: 1.0000
Epoch 3/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6531 - accuracy: 1.0000
Epoch 4/100
3/3 [==============================] - 0s 6ms/step - loss: 0.6362 - accuracy: 1.0000
Epoch 5/100
3/3 [==============================] - 0s 7ms/step - loss: 0.6171 - accuracy: 1.0000
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 0.5915 - accuracy: 1.0000
Epoch 7/100
3/3 [==============================] - 0s 7ms/step - loss: 0.5649 - accuracy: 1.0000
Epoch 8/100
3/3 [==============================] - 0s 7ms/step - loss: 0.5316 - accuracy: 1.0000
Epoch 9/100
3/3 [==============================] - 0s 7ms/step - loss: 0.4938 - accuracy: 1.0000
Epoch 10/100
3/3 [==============================] - 0s 5ms/step - loss: 0.4541 - accuracy: 1.0000
Epoch 11/100
3/3 [==========

# 2. 사이킷런

##### (1) iris 데이터

In [47]:
'''1. 데이터 불러오기'''
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
iris_dataset=load_iris()
# print(iris_dataset.keys(),iris_dataset)
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                    iris_dataset['target'], test_size=0.25, random_state=42)

'''2. K-Neighbors Classifier'''
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(train_input, train_label)
print("최근접 이웃 accuracy : {}".format(np.mean(knn.predict(test_input)==test_label)))

'''3. 비지도 학습'''
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)
k_means.fit(train_input)
print(train_label[k_means.labels_==0])
print(train_label[k_means.labels_==1])
print(train_label[k_means.labels_==2])

최근접 이웃 accuracy : 1.0
[2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]


##### (2) 단어 특징 추출

In [8]:
'''1. CountVectorizer'''
from sklearn.feature_extraction.text import CountVectorizer
text_data = ['나는 배가 고프다', '내일 점심 뭐먹지', '내일 공부해야겠다.', '점심 먹고 공부해야지']
count_vectorizer = CountVectorizer()
count_vectorizer.fit(text_data)
sentence = [text_data[0]]
print(count_vectorizer.vocabulary_)
print(count_vectorizer.transform(sentence).toarray())

'''2. TfidVectorizer'''
from sklearn.feature_extraction.text import TfidfVectorizer
text_data = ['나는 배가 고프다', '내일 점심 뭐먹지', '내일 공부해야겠디', '점심 먹고 공부해야지']
tfidf_vectorizer= TfidfVectorizer()
tfidf_vectorizer.fit(text_data)
print(tfidf_vectorizer.vocabulary_)
sentence = ['점심 먹고 공부해야지']
print(tfidf_vectorizer.transform(sentence).toarray())

{'나는': 3, '배가': 7, '고프다': 0, '내일': 4, '점심': 8, '뭐먹지': 6, '공부해야겠다': 1, '먹고': 5, '공부해야지': 2}
[[1 0 0 1 0 0 0 1 0]]
{'나는': 3, '배가': 7, '고프다': 0, '내일': 4, '점심': 8, '뭐먹지': 6, '공부해야겠디': 1, '먹고': 5, '공부해야지': 2}
[[0.         0.         0.61761437 0.         0.         0.61761437
  0.         0.         0.48693426]]


# 3. 자연어 토크나이징 도구

#### (1) 영어 토크나이징 라이브러리

In [10]:
'''안할거임'''

'안할거임'

#### (2) 한글 토크나이징 라이브러리 - KoNLPy

In [6]:
'''1. konlpy의 메서드 사용하기'''
from konlpy.tag import Okt
okt = Okt()
text = "한글 자연어 처리는 재밌다 이제부터 열심히 해야지ㅎㅎㅎ"
print(okt.morphs(text))
print(okt.morphs(text, stem=True))
print(okt.nouns(text))
print(okt.phrases(text))
print(okt.pos(text))
print(okt.pos(text, join=True))

'''2. konlpy 내장 데이터 사용하기'''
from konlpy.corpus import kolaw
from konlpy.corpus import kobill
print(kolaw.open('constitution.txt').read()[:20])
print(kobill.open('1809890.txt').read()[:10])

['한글', '자연어', '처리', '는', '재밌다', '이제', '부터', '열심히', '해야지', 'ㅎㅎㅎ']
['한글', '자연어', '처리', '는', '재밌다', '이제', '부터', '열심히', '하다', 'ㅎㅎㅎ']
['한글', '자연어', '처리', '이제']
['한글', '한글 자연어', '한글 자연어 처리', '이제', '자연어', '처리']
[('한글', 'Noun'), ('자연어', 'Noun'), ('처리', 'Noun'), ('는', 'Josa'), ('재밌다', 'Adjective'), ('이제', 'Noun'), ('부터', 'Josa'), ('열심히', 'Adverb'), ('해야지', 'Verb'), ('ㅎㅎㅎ', 'KoreanParticle')]
['한글/Noun', '자연어/Noun', '처리/Noun', '는/Josa', '재밌다/Adjective', '이제/Noun', '부터/Josa', '열심히/Adverb', '해야지/Verb', 'ㅎㅎㅎ/KoreanParticle']
대한민국헌법

유구한 역사와 전통에 
지방공무원법 일부개


#### (2) re 라이브러리

In [21]:
import re
pattern =" \W+"
re_pattern = re.compile(pattern)
print(re_pattern)
re_name = re.search("(\w+)", "wow, it is awesome")
re.split('\W', 'wow, it is world of word')
re.sub('\d', 'number', '7 candy')

re.compile(' \\W+')


'number candy'